package typesense

type ProductSkuDocument struct {
	ID                          string  `json:"id"`
	BatchID                     string  `json:"batch_id"`
	ProductSKUID                int64   `json:"product_sku_id"`
	CategoryCode                string  `json:"category_code"`
	CategoryID                  int64   `json:"category_id"`
	CategoryName                string  `json:"category_name"`
	CategorySlug                string  `json:"category_slug"`
	CategoryURL                 string  `json:"category_url"`
	DiscountPercentage          int64   `json:"discount_percentage"`
	DiscountTypeID              int64   `json:"discount_type_id"`
	DiscountTypeName            string  `json:"discount_type_name"`
	DiscountValue               int64   `json:"discount_value"`
	FormattedDiscountPercentage string  `json:"formatted_discount_percentage"`
	FormattedDiscountValue      string  `json:"formatted_discount_value"`
	FormattedProductPrice       string  `json:"formatted_product_price"`
	FormattedSellingPrice       string  `json:"formatted_selling_price"`
	IsDefault                   int64   `json:"is_default"`
	ProductID                   int64   `json:"product_id"`
	ProductImage                string  `json:"product_image"`
	ProductImageNoBackground    string  `json:"product_image_no_background"`
	ProductImageNoBackgroundURL string  `json:"product_image_no_background_url"`
	ProductImageURL             string  `json:"product_image_url"`
	ProductName                 string  `json:"product_name"`
	ProductPrice                int64   `json:"product_price"`
	ProductSkuMPN               string  `json:"product_sku_mpn"`
	ProductSkuName              string  `json:"product_sku_name"`
	ProductSkuNumber            string  `json:"product_sku_number"`
	ProductSold                 int64   `json:"product_sold"`
	ProductStatusID             int64   `json:"product_status_id"`
	ProductStatusName           string  `json:"product_status_name"`
	ProductStock                int64   `json:"product_stock"`
	ProductWeight               float64 `json:"product_weight"`
	SellingPrice                int64   `json:"selling_price"`
	ProductStatusRecord         string  `json:"product_status_record"`
	UOMAbbreviation             string  `json:"uom_abbreviation"`
	UOMID                       int64   `json:"uom_id"`
	UOMName                     string  `json:"uom_name"`
	IsInsurance                 int64   `json:"is_insurance"`
	IsPreorder                  int64   `json:"is_preorder"`
	PreorderDay                 int64   `json:"preorder_day"`
	PreorderTypeID              int64   `json:"preorder_type_id"`
	PreorderTypeName            string  `json:"preorder_type_name"`
	ProductConditionID          int64   `json:"product_condition_id"`
	ProductConditionName        string  `json:"product_condition_name"`
	ProductDescription          string  `json:"product_description"`
	ProductHeight               float64 `json:"product_height"`
	ProductLength               float64 `json:"product_length"`
	ProductMetaDescription      string  `json:"product_meta_description"`
	ProductMetaTitle            string  `json:"product_meta_title"`
	ProductSlug                 string  `json:"product_slug"`
	ProductURL                  string  `json:"product_url"`
	ProductVolumeWeight         float64 `json:"product_volume_weight"`
	ProductWidth                float64 `json:"product_width"`
	ReviewMessage               string  `json:"review_message"`
	ReviewRating                int64   `json:"review_rating"`
	ReviewsCount                int64   `json:"reviews_count"`
	StoreID                     int64   `json:"store_id"`
	StoreLocationName           string  `json:"store_location_name"`
	StoreName                   string  `json:"store_name"`
	StoreProductSlug            string  `json:"store_product_slug"`
	StoreSlug                   string  `json:"store_slug"`
	StoreStatusID               int64   `json:"store_status_id"`
	StoreStatusName             string  `json:"store_status_name"`
	StoreURL                    string  `json:"store_url"`
	Timestamp                   int64   `json:"timestamp"`
	TotalRating                 string  `json:"total_rating"`
	UploadDate                  int64   `json:"upload_date"`
}
